version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - echo Installing Entity Framework Core tools reference - .NET CLI
      - dotnet tool install --global dotnet-ef
  pre_build:
    commands:
      - dotnet restore 
      - echo "$RDS_DB_NAME"
      - echo Info about dbcontext
      - dotnet ef dbcontext info --project MedicaRental.API/MedicaRental.API.csproj
      - echo Updateing DataBase 
      - dotnet ef database update --project MedicaRental.API/MedicaRental.API.csproj
  build:
    commands:
      - dotnet build 
  post_build:
    commands:
      - dotnet publish MedicaRental.API/MedicaRental.API.csproj -c Release -o ./app
artifacts:
  files:
    - '**/*'
  base-directory: 'app' 